#Hugo configuration
title = "DDDPRoejcts"
baseURL = "https:\/\/dddprojects.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
cookieDomain = "poop"

[params]
loginId = "1758904"
subfolder = ""
